version: '3.8'

services:
    api:
        container_name: nestjs_api
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 3306:3306
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/login
            - /usr/src/login/node_modules
        restart: unless-stopped

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless stopped
        environment:
            MYSQL_ROOT_PASSWORD: geronim0


networks:
    nesjs-network: